### ISSUE TITLE
VZD: Automate the location association for CR3 & non-CR3 crash records

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#565] opened 2019-12-29 22:41 UTC
The scope of #483 was specific to setting up the columns required and performing a one-off association for non-CR3 records. 

In discussions for that issue we've identified more work that needs to be tackled for the long-term management of associating locations to crashes: 

- [ ] Automate CR3 records association to locations
- [ ] Automate non-CR3 records association to locations
- [ ] At a minimum, these association scripts could run as an hourly or daily job, but ideally, each script would run on new record creation, or when coordinates get updated on an existing record

We should hold off on tackling this work until we have a more comprehensive dataset of locations which is currently pending from the VZ team.

**Comment by JaceDeloney** [comment] 2020-01-22 20:47
Outstanding tasks:

- Need to define the cadence and need for running these scripts
- Import of new locations (waiting for VZ team's new locations file)
- Create a new column for CR3 locations
- Determine whether we can get rid of the association table

**Comment by JaceDeloney** [comment] 2020-01-22 20:51
@JaceDeloney to create an epic to break this work up. This work will begin in Sprint 17, specifically the removal of the association table between crashes & locations.

**Comment by JaceDeloney** [comment] 2020-02-05 20:46
This is a duplicate of #672.

**Closed by JaceDeloney** 2020-02-05 20:46 UTC
Labels: Need: 1-Must Have, Project: Vision Zero Crash Data System, Service: Dev, Type: Feature, Workgroup: VZ
